image: maven:latest

stages:          
  - build
  - test
  - package

build:
  stage: build
  only:
    - main
    - merge_requests
  script:
    - echo "Building project"
    - mvn clean compile

test:
  stage: test
  only:
    - master
    - merge_requests
  script:
    - echo "Running tests"
    - mvn clean test

pages:
  stage: package
  script:
    - echo "Building Javadoc"
    - mvn javadoc:javadoc
  artifacts:
    paths:
      - public
  only:
    - web